find_trending_companies:
  description: >
    Find the top trending companies in the news in {sector} by searching the latest news until {current_date}. Find new companies that you've not found before.
  expected_output: >
    A list of trending companies in {sector}
  agent: trending_company_finder
  output_file: output/{sector}_trending_companies.json

research_trending_companies:
  description: >
    Given a list of trending companies, provide detailed analysis of each company in a report by searching online
  expected_output: >
    A report containing detailed analysis of each company
  agent: financial_researcher
  context:
    - find_trending_companies
  output_file: output/{sector}_research_report.json

pick_best_company:
  description: >
    Based on the research findings of all companies, choose the single most promising company for investment.

    Step 1: Analyze the research data and select the company with the strongest investment potential. 
    Summarize the rationale in a single sentence, limited to 100 words.

    Step 2: Use the push notification tool (PushNotificationTool) to send a notification to the user.
    The message must include:
      - The name of the selected company
      - A short reason within 30 words to explain the choice

    Step 3: Provide a detailed written report explaining:
      - Why this company was selected, including its market position, growth potential, and investment appeal
      - Why the other companies were not selected, with a brief comparison
  expected_output: >
    The chosen company and why it was chosen; the companies that were not selected and why they were not selected.
  agent: stock_picker
  context:
    - research_trending_companies
  output_file: output/{sector}_decision.md
